[package]
name = "lua"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "^1.15.0", features = ["full", "tracing"] }
pest = "2.1.3"
pest_derive = "2.1.0"

anyhow = "1.0.52"
thiserror = "1.0.30"

async-recursion = "1.0.0"
lazy_static = "1.4.0"
futures = "0.3.19"

structopt = "0.3.25"
