[package]
name = "gor"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"

authors = ["Andrew Aylett <andrew@aylett.co.uk>"]
license = "Apache-2.0"
description = "An implementation of Go, as an interpreter written in Rust"
repository = "https://github.com/andrewaylett/gor"

[workspace]
members = [".", "packages/*"]
default-members = [".", "packages/*"]

[dependencies]
gor-ast = { version="0.1.0", path="packages/ast" }
gor-parse = { version="0.1.0", path="packages/parse" }
gor-eval = { version="0.1.0", path="packages/eval" }

tokio = { version = "^1.15.0", features = ["full", "tracing"] }
pest = "2.1.3"
pest_derive = "2.1.0"

anyhow = "1.0.52"
thiserror = "1.0.30"

async-recursion = "1.0.0"
lazy_static = "1.4.0"
futures = "0.3.19"

structopt = "0.3.25"

[dev-dependencies]
pretty_assertions = "1.2.1"
