[package]
name = "gor-ast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gor-parse = { path="../parse" }

pest = "2.1.3"
pest_derive = "2.1.0"

thiserror = "1.0.30"

lazy_static = "1.4.0"

[dev-dependencies]
pretty_assertions = "1.2.1"
anyhow = "*"
