[package]
name = "gor-ast"
version = "0.1.0"
edition = "2021"

authors = ["Andrew Aylett <andrew@aylett.co.uk>"]
license = "Apache-2.0"
description = "Abstract syntax trees for Go modules"
repository = "https://github.com/andrewaylett/gor"

[dependencies]
gor-parse = { version="0.1.0", path="../parse" }
gor-core = { version="0.1.0", path="../core" }

pest = "2.5.3"

thiserror = "1.0.38"

backtrace = "0.3.67"

[dev-dependencies]
pretty_assertions = "1.3.0"
anyhow = "1.0.68"
