[package]
name = "gor-parse"
version = "0.1.0"
edition = "2021"

authors = ["Andrew Aylett <andrew@aylett.co.uk>"]
license = "Apache-2.0"
description = "A Pest-based parser for Go modules"
repository = "https://github.com/andrewaylett/gor"

[dependencies]
pest = "2.4.1"
pest_derive = "2.4.1"

thiserror = "1.0.38"

lazy_static = "1.4.0"

[dev-dependencies]
pretty_assertions = "1.3.0"
