[package]
name = "gor-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.38"

lazy_static = "1.4.0"
regex = "1.7.0"

[dev-dependencies]
pretty_assertions = "1.3.0"
anyhow = "1.0.68"
