[package]
name = "gor-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.31"

lazy_static = "1.4.0"
regex = "1.6.0"

[dev-dependencies]
pretty_assertions = "1.2.1"
anyhow = "1.0.60"
