[package]
name = "gor-eval"
version = "0.1.0"
edition = "2021"

authors = ["Andrew Aylett <andrew@aylett.co.uk>"]
license = "Apache-2.0"
description = "The Gor interpreter"
repository = "https://github.com/andrewaylett/gor"

[dependencies]
gor-ast = { version="0.1.0", path="../ast" }
gor-parse = { version="0.1.0", path="../parse" }

tokio = { version = "^1.15.0", features = ["full", "tracing"] }
pest = "2.1.3"
pest_derive = "2.1.0"

anyhow = "1.0.57"
thiserror = "1.0.30"

async-recursion = "1.0.0"
async-trait = "*"
lazy_static = "1.4.0"
futures = "0.3.19"

[dev-dependencies]
pretty_assertions = "1.2.1"
