[package]
name = "gor-eval"
version = "0.1.0"
edition = "2021"

authors = ["Andrew Aylett <andrew@aylett.co.uk>"]
license = "Apache-2.0"
description = "The Gor interpreter"
repository = "https://github.com/andrewaylett/gor"

[dependencies]
gor-ast = { version="0.1.0", path="../ast" }
gor-parse = { version="0.1.0", path="../parse" }
gor-core = { version="0.1.0", path="../core" }
gor-linker = { version="0.1.0", path="../linker" }
gor-loader = { version="0.1.0", path="../loader" }

tokio = { version = "^1.20.1", features = ["full", "tracing"] }

thiserror = "1.0.31"

async-trait = "0.1.56"
lazy_static = "1.4.0"
futures = "0.3.21"

[dev-dependencies]
pretty_assertions = "1.2.1"
anyhow = "1.0.58"
pest = "2.2.1"
